### ISSUE TITLE
Refactor anti raid nuke

### ISSUE THREAD

**Issue by almostSouji** [Naval-Base/yuudachi#1064]
- More useful parameters (ceill, floor, confusables, zalgo, pattern case insensitive, )
- Figure out what the recently discovered case id insertion error is and fix it
- Show progress
- More verbose output
- Better format output (using ansi, if the line length is guaranteed short?)
- New version of anti raid nuke which takes or parses ids (file/modal)

**Comment by JPBM135** [comment]
Maybe add a filter to `noPfp` or an avatar to match a hash using a library like `sharp-phash`
The argument can possibly be an user to use as an example or an `cdn` URL
