### ISSUE TITLE
Feature: Flag known scam usernames

### ISSUE THREAD

**Issue by JPBM135** [Naval-Base/yuudachi#1067]
## Using a list of regexes provided by the Open Source Aero bot and refactored by me:
```js
[
	{
		name: 'Discord_HypeSquad',
		regex: /discord\s+hype\s*squad/i,
	},
	{
		name: 'Discord_Events_Academy',
		regex: /(hype\s*squad|discord)\s+(events?|academy|team|mail)/i,
	},
	{
		name: 'Discord_Developers',
		regex: /discord\s+(developers?|api|bots?|message)?/i,
	},
	{
		name: 'Discord_Moderators',
		regex: /^discord\s+moderators?$/i,
	},
	{
		name: 'Academy_Staff',
		regex: /^academy\s+(staff|moderator)s?/i,
	},
	{
		name: 'Mod_Developers_Academy',
		regex: 	/(mod(erator)?('?s)?|hype\s*squad|developers?)\s+(academy|message|exam|team|events?)/i,
	},
	{
		name: 'Contact_Hype',
		regex: /contact\s*(hype|events?)/i,
	},
	{
		name: 'HypeSquad_Events',
		regex: /(hype)\s+(events?|messages?|apply|team)/i,
	},
];
```

Link: [Aero Repo](https://ravy.dev/aero/aero/-/blob/08e7d770b1e3c2b1fa5cf28e43df5332742db7de/src/events/guildMemberAdd.js)

**Comment by almostSouji** [comment]
We currently flag suspicious accounts in a mod forum post, I much prefer that approach to automated actions, as it allows us to be much more lenient with what we flag.

Currently, this system implements the pre- and suffix wildcards discord uses for their automod and a modal command as "editor" and also takes care of confusables, special characters and whitespace.

Eventually, this should move to yuudachi as well

**Comment by almostSouji** [comment]
We could consider a sort of manually toggled anti raid mode eventually, which could automatically action these and maybe even adapt the thresholds for other anti spam/scam filters
