### ISSUE TITLE
Log reply information

### ISSUE THREAD

**Issue by almostSouji** [Naval-Base/yuudachi#1074]
Message replies are currently largely ignored in your logging mechanism.

This includes mention spam executed with mentioning replies that cannot be exposed through the currently logged information.
This information could and probably should be introduced in message logging mechanisms

![image](https://user-images.githubusercontent.com/26532370/181794579-2826efbf-b8c0-449c-9785-7d78bd3ec050.png)

- Log the message id (and maybe link) of the message that is being replied to
- Log when a user is mentioned through the reply mechanism, as it does not turn up in the logged message content, as with other message deletions.

**Comment by JPBM135** [comment]
If there's a way to differ non pinging replies from pinging ones, maybe the pinging ones should count against the mention threshold

**Comment by almostSouji** [comment]
I'm not sure if incorporating it into auto-moderation is a good idea. Fairly rapid mention replies are a valid strategy in support when helping multiple people
