### ISSUE TITLE
feature: automatic token expiration

### ISSUE THREAD

**Issue by JPBM135** [Naval-Base/yuudachi#1075]
Since discord.js sever is all about developing bots, sometimes members let their tokens leak. The majority of the time the members instruct the user to reset his token but there are times when like this doesn't happen or the token isn't seen at all.

## Propose

- Get the token (Which can be user or bot tokens) that has been sent (Maybe delete the message)
- Upload them to a Github repo
- Wait an amount of time so that the `Secrets scanning` can be executed resetting the token and notifying the user
- Delete the file (Or maybe not, since the token will expire anyway)

**Comment by almostSouji** [comment]
We have attempted to scan for tokens before and it has gone horrendously wrong with a code-based server, where dot accessor chaining is a common occurrence (the regex for tokens really can't be all that strict)

uploading tokens in bulk to github can look like malicious intent and has been actioned by github before, unsure if the risk is worth it

**Comment by JPBM135** [comment]
I think that if we delete it some time after posting, github will not flag, but it is a high risk indeed

**Comment by almostSouji** [comment]
If you have a regex in mind we could test run that to flag things on a test bot for a while, to see if it may cause more confusion than necessary. We have attempted detecting and deleting posts including tokens before and reverted the change

this has now become even more of an issue, since interaction response stack traces/api errors often include webhook tokens

**Comment by JPBM135** [comment]
Maybe instead of deleting the message, we send a DM to the user or a chat warning

**Comment by almostSouji** [comment]
Running the test on another bot right now, don't think it has much use, since discord natively implemented token scans, but the approach seems solid to not cause false positives

**Comment by JPBM135** [comment]
Maybe this should be closed in favor of keeping it in Cerb? @almostSouji
