### ISSUE TITLE
Modcommand to clear messages

### ISSUE THREAD

**Issue by almostSouji** [Naval-Base/yuudachi#1079]
Moderation command to clean messages

- Slash command from-to ~~(also allow use of ms duration formats?) could also have toggles like ignoring ignored mod roles or similar, unsure yet~~
- Message context command to clean up to that message
- Some upper bounds (a few hours?) to not run into accidental channel nukes

**Comment by JPBM135** [comment]
Maybe use some filters like the anti-raid, like pattern, author(s), mentioned users/roles, zalgo/confusables, urls (domains), embeds

Maybe implement fuzzy hashing as an option on the message context command to exclude similar messages

**Comment by almostSouji** [comment]
First iteration: https://github.com/Naval-Base/yuudachi/pull/1083 (missing context command, requires a larger scale reactor of command handling to support context commands without requiring specific names as a hacky workaround)

**Comment by JPBM135** [comment]
We could integrate the parseData function from the Anti-Raid on the from-to to allow more data types

**Comment by JPBM135** [comment]
About fuzzy matching: 

Look at this library: https://www.npmjs.com/package/fuse.js?activeTab=readme

**Comment by almostSouji** [comment]
> **Note**
> Will be resolved with the message context menu command in the linked PR, further possible extensions should be handled in standalone PRs or feature reuquests
