### ISSUE TITLE
guide to self host?

### ISSUE THREAD

**Issue by salsawij** [Naval-Base/yuudachi#1136]

**Comment by JPBM135** [comment]
- Run `yarn --immutable`
- Run the docker compose images on the `/packages/yuudachi` path
- Provide all the envs on an .env file in the `/packages/yuudachi` path (You can search for `process.env`)
- Run `yarn start:dev`

**Comment by almostSouji** [comment]
The bot is open source for screening purposes and to serve as an example of discord.js use. We do not offer extended support for self-hosting and configuring all the individual parts that make yuudachi work as it is meant to be working.
