### ISSUE TITLE
Website: Specify that mod and target queries are done by ID, not tag

### ISSUE THREAD

**Issue by almostSouji** [Naval-Base/yuudachi#907]
![image](https://user-images.githubusercontent.com/26532370/103432886-98eb0600-4be7-11eb-883d-dbdc950a905d.png)
 Possibly add "by discord user ID" or similar
 
 The current layout suggests that columns are searched by the shown column value (this is the case for numerical input and reason). However mod and target are queried by ID, the user tag (shown) does not work.

**Comment by iCrawl** [comment]
Not sure how possible without much work. The name at the top is given from the column name. 

Renaming the column to `Mod Id` isn't necessarily possible here because thats where the tag is displayed.
