### ISSUE TITLE
Website: Discern slot names more clearly in case modal

### ISSUE THREAD

**Issue by almostSouji** [Naval-Base/yuudachi#909]
![image](https://user-images.githubusercontent.com/26532370/103432941-7d342f80-4be8-11eb-9651-d711ff6d4e5d.png)

Visuals could be clearer here, considering bolding the title and/or putting a `:` in place

**Comment by iCrawl** [comment]
This already is bold, same as for the tags.

![image](https://user-images.githubusercontent.com/20760160/103436663-8fc95b80-4c1e-11eb-8e91-a0252a36aebf.png)

Not sure why it doesn't seem to be for you? The css has a font-weight of 500 on it.

**Comment by almostSouji** [comment]
![image](https://user-images.githubusercontent.com/26532370/103437590-b0e37980-4c29-11eb-8ffd-e0dc6552b878.png)

Interesting one, the weight 500 is indeed there in inspect, however, is much more pronounced in chrome (right) than it is in Firefox (left)

**Comment by iCrawl** [comment]
I blame this on firefox then 🙃

**Comment by almostSouji** [comment]
interesting nonetheless ^^
