### ISSUE TITLE
Website: Edit button prompts old content, although table view updated

### ISSUE THREAD

**Issue by almostSouji** [Naval-Base/yuudachi#911]
After updating properties clicking the edit button will get the values from before the edit back in the modal. The table row itself in the case view is already updated.

![image](https://user-images.githubusercontent.com/26532370/103432995-c173ff80-4be9-11eb-8b47-87f1242babda.png)

The edit modal still shows the previous reason "first". However, this resolves itself if the modal is closed and re-opened, thus probably very minor, maybe even "wontfix" territory.

**Comment by iCrawl** [comment]
This seems to be a browser issue:

![image](https://user-images.githubusercontent.com/20760160/103436735-51806c00-4c1f-11eb-9fa6-7b9b130200a1.png)
![image](https://user-images.githubusercontent.com/20760160/103436737-55ac8980-4c1f-11eb-980a-e3026bcae231.png)

**Comment by almostSouji** [comment]
Since case toast confirmations were added this issue disappeared - maybe something with that popup makes the browser refresh state? Can no longer reproduce

**Comment by iCrawl** [comment]
I guess we'll just close this for now then.
