### ISSUE TITLE
Handler: No feedback on negative duration

### ISSUE THREAD

**Issue by almostSouji** [Naval-Base/yuudachi#920]
- Command is swallowed without any feedback (`/duration <id> -20m`)
- Expected: Ephemeral message informing that duration can't be negative
- Note: Initial role command does reject negative input

**Comment by iCrawl** [comment]
Both of those mentioned commands include the same logic for rejection on an invalid duration though 🤔

**Comment by iCrawl** [comment]
This works as expected for me: 
![image](https://user-images.githubusercontent.com/20760160/103454363-6cb4af80-4ce3-11eb-8c81-4bece64ca3d5.png)

The first is from the restrict command, the latter from the duration one.

**Comment by almostSouji** [comment]
can indeed not reproduce, might've been network issues
